### ISSUE TITLE
can not start complie maybe something error?

### ISSUE THREAD

**Issue by zhiyuan823** [idleberg/vscode-nsis#25]
nice to meet you, dear author.

 I am sure current edit file is *.nsi. when I click toolbar button 'NSIS:save & Complie Script" or ''NSIS:save & Complie Script(strict)" . There is nothing happend.  There is noting output to NSIS console.  It seem like NSIS Complier was did not started.

I try to run task whoes named "Build" or "Build(strict)" in Terminal. NSIS is works. So, I guess there is something error in click buttom operation.

my NSIS options

```
"nsis.alwaysOpenBuildTask": true
"nsis.alwaysShowOutput": true
"nsis.compiler.customArguments": []
"nsis.compiler.overrideCompression": true
"nsis.compiler.pathToMakensis": "d:\\Dropbox\\Tools\\Dev\\NSIS\\makensis.exe"
"nsis.compiler.preprocessMode": "Safe PPO"
"nsis.compiler.strictMode": false
"nsis.compiler.verbosity": "3"
"nsis.muteANSIDeprecationWarning": false
"nsis.processHeaders": false
"nsis.showFlagsAsObject": true
"nsis.showNotifications": true
"nsis.showVersionAsInfoMessage": false
"nsis.useWineToRun": false
```

NSIS plugin version: v3.40.1

VSCode info:
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by idleberg** [comment]
Could you provide an [MRE](https://stackoverflow.com/help/minimal-reproducible-example) script that reproduces the error?

**Comment by idleberg** [comment]
Actually, I wonder if the error is in your VSCode settings. Could you edit your initial post and add the lines before "found in user settings"?

**Comment by zhiyuan823** [comment]
thansk for your replay, I try to make this more clear.

**Comment by bricebm** [comment]
I am having this same issue.  .nsi files that uses to compile now produce no output.  I would be happy to provide anything needed to help troubleshoot this issue.  NSIS extension options are default other than specifying the path to makensis.

Thanks  

Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.18363

{
    "nsis.compiler.pathToMakensis": "C:\\Program Files (x86)\\NSIS\\makensis.exe"
}

**Comment by idleberg** [comment]
@bricebm Your settings file isn't encoded properly, backslashes need to be escaped in JSON. See the [example](https://github.com/idleberg/vscode-nsis#makensis) in the README.

**Comment by zhiyuan823** [comment]
In my settings, the path is  "d:\\Dropbox\\Tools\\Dev\\NSIS\\makensis.exe", but the problem remains. I don't know how to provide you with more debugging information.

**Comment by bricebm** [comment]
@idleberg...I made the correction to the path and it still behaves the same.  Clicking the Save and Compile script produces no output.  

{
    "nsis.compiler.pathToMakensis": "C:\\Program Files (x86)\\NSIS\\makensis.exe"
}

Found the following in "C:\Users\bmitch03\AppData\Roaming\Code\logs\20210502T094626\exthost1\exthost.log" when clicking the Show Version button.  Save and Compile and Save and Compile strict still produce no output and I find no entries in the logs when clicking those buttons.  Not sure if this helps.  Thanks for you work on this extension.

021-05-02 09:56:18.662] [exthost] [error] SyntaxError: Unexpected token W in JSON at position 246
                at JSON.parse (<anonymous>)
                at c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:13331
                at d (c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:2185)
                at Object.next (c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:1489)
                at c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:1215
                at new Promise (<anonymous>)
                at Ue (c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:1012)
                at zo (c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:11116)
                at c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:11005
                at d (c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:2185)
                at Object.next (c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:1489)
                at c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:1215
                at new Promise (<anonymous>)
                at Ue (c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:1012)
                at ga (c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:10763)
                at c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:10591
                at d (c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:2185)
                at Object.next (c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:1489)
                at c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:1215
                at new Promise (<anonymous>)
                at Ue (c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:1012)
                at Uo (c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:1:10415)
                at oe (c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:22:1675)
                at Yi (c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:22:4908)
                at processTicksAndRejections (internal/process/task_queues.js:97:5)
                at async c:\Users\bmitch03\.vscode\extensions\idleberg.nsis-3.40.1\lib\extension.js:22:8069
                at async S._executeContributedCommand (c:\Program Files\Microsoft VS  Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:106762) extension.nsis.show-version

**Comment by idleberg** [comment]
Thanks for the additional info. I now can reproduce the problem and hopefully fix it in the next couple of days!

**Comment by idleberg** [comment]
Could you please test this in v3.40.2?

**Comment by bricebm** [comment]
Upgraded to 3.40.2 and plugin is working as expected now. 

Thanks for the help and the great plugin

**Comment by zhiyuan823** [comment]
update to 3.40.2, everything is ok. good job! thanks a lot.  I like your soft very much!

**Comment by idleberg** [comment]
Thanks again for reporting the issue. Please consider rating this extension on the[ Marketplace](https://marketplace.visualstudio.com/items?itemName=idleberg.nsis).
